STRINGS: dict = {
    'id': {
        'splash_loading'    : 'Memuat aplikasi...',
        'splash_subtitle'   : 'Auto-Player Piano · Sky & Piano Tiles',
        'window_title'      : 'Song Player – Pilih File Lagu',
        'header_title'      : '🎵  Song Auto-Player',
        'header_subtitle'   : 'Pilih folder → pilih lagu → mainkan',
        'folder_nav_panel'  : 'Navigasi Folder',
        'back_btn'          : '← Kembali',
        'add_folder_btn'    : '+ Tambah',
        'remove_folder_btn' : '− Hapus',
        'add_folder_dialog' : 'Pilih Folder Lagu',
        'no_folder_selected': '  Pilih folder untuk melihat file lagu...',
        'speed_label'       : 'Kecepatan Putar',
        'speed_range'       : '0.25×  ──────  3.00×',
        'diff_beginner'     : ('Pemula',   '#6BCB77'),
        'diff_learning'     : ('Belajar',  '#74C0FC'),
        'diff_relaxed'      : ('Santai',   '#A9C0D6'),
        'diff_normal'       : ('Normal',   '#CDD6F4'),
        'diff_advanced'     : ('Mahir',    '#FFA94D'),
        'diff_pro'          : ('Pro',      '#FF6B6B'),
        'diff_master'       : ('Master',   '#DA77F2'),
        'col_no'            : 'No',
        'col_title'         : 'Judul',
        'col_size_kb'       : 'Ukuran',
        'file_count_fmt'    : '{shown}/{total} file',
        'file_count_all'    : '{total} file',
        'status_file'       : '  {path}  |  {size:,} bytes  |  {mtime}',
        'play_btn'          : '▶  Mainkan File Ini',
        'cancel_btn'        : 'Batal',
        'warn_title'        : 'Pilih File',
        'warn_msg'          : 'Silakan pilih file dari daftar terlebih dahulu.',
        'no_file_msg'       : 'Tidak ada file yang dipilih. Keluar.',
        'mido_title'        : 'Mido Missing',
        'mido_msg'          : "Library 'mido' tidak ditemukan.\nJalankan: pip install mido",
        'palette_celestial' : 'Zinc',
        'palette_grand'     : 'Slate',
        'info_btn'          : 'Info',
        'info_title'        : 'Tentang Aplikasi',
    },
    'en': {
        'splash_loading'    : 'Loading application...',
        'splash_subtitle'   : 'Piano Auto-Player · Sky & Piano Tiles',
        'window_title'      : 'Song Player – Select Song File',
        'header_title'      : '🎵  Song Auto-Player',
        'header_subtitle'   : 'Select folder → choose song → play',
        'folder_nav_panel'  : 'Folder Navigator',
        'back_btn'          : '← Back',
        'add_folder_btn'    : '+ Add',
        'remove_folder_btn' : '− Remove',
        'add_folder_dialog' : 'Select Song Folder',
        'no_folder_selected': '  Select a folder on the left to view song files...',
        'speed_label'       : 'Playback Speed',
        'speed_range'       : '0.25×  ──────  3.00×',
        'diff_beginner'     : ('Beginner',  '#6BCB77'),
        'diff_learning'     : ('Learning',  '#74C0FC'),
        'diff_relaxed'      : ('Relaxed',   '#A9C0D6'),
        'diff_normal'       : ('Normal',    '#CDD6F4'),
        'diff_advanced'     : ('Advanced',  '#FFA94D'),
        'diff_pro'          : ('Pro',       '#FF6B6B'),
        'diff_master'       : ('Master',    '#DA77F2'),
        'col_no'            : 'No',
        'col_title'         : 'Title',
        'col_size_kb'       : 'Size',
        'file_count_fmt'    : '{shown}/{total} files',
        'file_count_all'    : '{total} files',
        'status_file'       : '  {path}  |  {size:,} bytes  |  {mtime}',
        'play_btn'          : '▶  Play This File',
        'cancel_btn'        : 'Cancel',
        'warn_title'        : 'Select File',
        'warn_msg'          : 'Please select a file from the list first.',
        'no_file_msg'       : 'No file selected. Exiting.',
        'mido_title'        : 'Mido Missing',
        'mido_msg'          : "Library 'mido' not found.\nRun: pip install mido",
        'palette_celestial' : 'Zinc',
        'palette_grand'     : 'Slate',
        'info_btn'          : 'Info',
        'info_title'        : 'About',
    },
}
