THEMES: dict = {
    'celestial': {
        'dark': {
            'BG'        : '#09090B',
            'PANEL'     : '#18181B',
            'ACCENT'    : '#FAFAFA',
            'ACCENT_HOV': '#D4D4D8',
            'TEXT'      : '#FAFAFA',
            'SUBTEXT'   : '#71717A',
            'ENTRY_BG'  : '#27272A',
            'BTN_HOV'   : '#27272A',
            'ROW_ALT'   : '#111113',
            'SEL_BG'    : '#3F3F46',
            'BORDER'    : '#27272A',
        },
        'light': {
            'BG'        : '#FFFFFF',
            'PANEL'     : '#F4F4F5',
            'ACCENT'    : '#18181B',
            'ACCENT_HOV': '#3F3F46',
            'TEXT'      : '#09090B',
            'SUBTEXT'   : '#71717A',
            'ENTRY_BG'  : '#FFFFFF',
            'BTN_HOV'   : '#D4D4D8',
            'ROW_ALT'   : '#FAFAFA',
            'SEL_BG'    : '#E4E4E7',
            'BORDER'    : '#E4E4E7',
        },
    },
    'grand_piano': {
        'dark': {
            'BG'        : '#020817',
            'PANEL'     : '#0F172A',
            'ACCENT'    : '#818CF8',
            'ACCENT_HOV': '#6366F1',
            'TEXT'      : '#F8FAFC',
            'SUBTEXT'   : '#64748B',
            'ENTRY_BG'  : '#1E293B',
            'BTN_HOV'   : '#1E293B',
            'ROW_ALT'   : '#050E1A',
            'SEL_BG'    : '#312E81',
            'BORDER'    : '#1E293B',
        },
        'light': {
            'BG'        : '#FFFFFF',
            'PANEL'     : '#F8FAFC',
            'ACCENT'    : '#6366F1',
            'ACCENT_HOV': '#4F46E5',
            'TEXT'      : '#0F172A',
            'SUBTEXT'   : '#64748B',
            'ENTRY_BG'  : '#FFFFFF',
            'BTN_HOV'   : '#C7D2FE',
            'ROW_ALT'   : '#F1F5F9',
            'SEL_BG'    : '#E0E7FF',
            'BORDER'    : '#E2E8F0',
        },
    },
}
